[tool.poetry]
name = "fastapi-cli"
version = "1.0.0"
description = "Managing FastAPI projects made easy."
authors = [
    "liangshihua <sxhx.liang@gmail.com>",
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/sxhxliang/fastapi-cli"
homepage = "https://github.com/sxhxliang/fastapi-cli"

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]


[tool.poetry.dependencies]
python = "^3.6.1"
typer = "^0.3.2"
bullet = "^2.2.0"
cookiecutter = "^1.7.2"
pydantic = { extras = ["email"], version = "^1.7.2" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autoflake = "^1.4"
flake8 = "^3.8.4"
mypy = "^0.790"
isort = "^5.0"
pre-commit = "^2.8.2"
black = "^20.8b1"
pytest-cov = "^2.10.1"

[tool.poetry.scripts]
fastapi-cli = 'fastapi_cli.main:app'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
